# app/constants/roles.py

# System roles
SYSTEM_ADMIN = "admin"
TENANT = "tenant"

# Group roles
GROUP_OWNER = "GROUP_OWNER"
GROUP_MANAGER = "GROUP_MANAGER"
GROUP_MEMBER = "GROUP_MEMBER"

VALID_SYSTEM_ROLES = {SYSTEM_ADMIN, TENANT}

VALID_GROUP_ROLES = {GROUP_OWNER, GROUP_MANAGER, GROUP_MEMBER}